version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  # security updates for vulnerabilities in gomod files
  - package-ecosystem: "gomod"
    directory: "/"    
    labels: ["security-update"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "SEC(update)"
  - package-ecosystem: "gomod"
    directory: "/test/acceptance_with_go_client"    
    labels: ["security-update"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "SEC(update)"
  - package-ecosystem: "gomod"
    directory: "/test/benchmark_bm25"    
    labels: ["security-update"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "SEC(update)"
