services:
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      SCHEMA_PROVIDER_URL: etcd:2379
    image: semitechnologies/contextionary:cs0.13.0-v0.4.7
    ports:
    - 9999:9999
  esvector:
    environment:
      ES_JAVA_OPTS: -Xms500m -Xmx500m
      discovery.type: single-node
      xpack.security.enabled: 'false'
    image: semitechnologies/esvector:7.1.0
    ports:
    - 9201:9200
    - 9301:9300
  etcd:
    command:
    - --name
    - s1
    - --data-dir
    - /etcd-data
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://0.0.0.0:2379
    - --listen-peer-urls
    - http://0.0.0.0:2380
    - --initial-advertise-peer-urls
    - http://0.0.0.0:2380
    - --initial-cluster
    - s1=http://0.0.0.0:2380
    - --initial-cluster-token
    - tkn
    - --initial-cluster-state
    - new
    entrypoint: /usr/local/bin/etcd
    image: gcr.io/etcd-development/etcd:v3.3.8
    ports:
    - 2379:2379
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    - --config-file
    - config.yaml
    depends_on:
    - esvector
    image: semitechnologies/weaviate:0.22.4
    ports:
    - 8080:8080
    restart: on-failure:0
    volumes:
    - ./config.yaml:/config.yaml
version: '3.4'
