version: '3.4'
services:
  t2v-transformers:
    image: gsi/t2v
    ports:
     - "8080:8080"
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
      # NVIDIA_VISIBLE_DEVICES: all # enable if running with CUDA 
