maximum_allowed_collections_count: 7
autoschema_enabled: true
async_replication_disabled: false
tenant_activity_read_log_level: info
tenant_activity_write_log_level: info
query_slow_log_enabled: true
query_slow_log_threshold: 100ms
inverted_sorter_disabled: false
usage_scrape_interval: 60m
usage_gcs_bucket: weaviate-usage
usage_gcs_prefix: billing
