maximum_allowed_collections_count: 70
autoschema_enabled: true
async_replication_disabled: false
tenant_activity_read_log_level: info
tenant_activity_write_log_level: info
query_slow_log_enabled: true
query_slow_log_threshold: 1ms
inverted_sorter_disabled: false

# authentication_oidc_username_claim: "sub"
# authentication_oidc_client_id: "<client_id>"
# authentication_oidc_issuer: "<issuer_url>"
# authentication_oidc_groups_claim: "teams"
